enabled: true
aws:
  accessKeyID: accesskey
  secretAccessKey: secretkey
  region: region
  arn: ""

installation:
  name: name

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/aws-servicequotas-operator"
  tag: "[[ .Version ]]"
registry:
  domain: docker.io

pod:
  user:
    id: 1000
  group:
    id: 1000

resources:
  limits:
    cpu: 250m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

global:
  podSecurityStandards:
    enforced: false
